// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (

	"ucenter-api/internal/svc"
	
)

func RegisterHandlers(r *Routes, serverCtx *svc.ServiceContext) {
	// 中间件
	register := NewRegisterHandler(serverCtx)
	registerRouter := r.Group()
	registerRouter.Post("/uc/register/phone", register.Register)
	registerRouter.Post("/uc/mobile/code", register.SendCode)
	loginGroup := r.Group()
	login := NewLoginHandler(serverCtx)
	loginGroup.Post("/uc/login",login.Login)
	loginGroup.Post("/uc/check/login",login.CheckLogin)
}
