// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"market-api/internal/svc"
)

func MarketHandlers(r *Routers, serverCtx *svc.ServiceContext) {
	//如果要有中间件 怎么办？
	rate := NewExchangeRateHandler(serverCtx)
	rateGroup := r.Group()
	rateGroup.Post("/exchange-rate/usd/:unit",rate.UsdRate)

	market := NewMarketHandler(serverCtx)
	marketGroup := r.Group()
	marketGroup.Post("/symbol-thumb-trend",market.SymbolThumbTrend)
	// marketGroup.Post("/symbol-thumb", market.SymbolThumb)

}
